spring:
  jpa:
    hibernate:
      ddl-auto: none
    autoconfigure: false
  flyway:
    enabled: false
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration