server:
  shutdown: graceful
  tomcat:
    connection-timeout: 5s
    keep-alive-timeout: 15s
    accept-count: 100
    threads:
      max: 200
      min-spare: 5


springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs

spring:
  application:
    name: control-energy
  data:
    redis:
      url: redis://127.0.0.1:6379
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      maximum-pool-size: 15
      connection-timeout: 2000
      idle-timeout: 1000
  flyway:
    locations:
      - db/migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, flyway, heapdump, info
  endpoint:
    prometheus:
      enabled: true
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
  metrics:
    enabled: true
    tags:
      application: ${spring.application.name}

logging:
  pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

api:
  common:
    version: 1.0.0
    title: Gastos API
    description: Control consumes
    contact:
      email: fabricio.jacob@outlook.com